### ISSUE TITLE
Upgrading a jupyterhub instance

### ISSUE THREAD

**Issue by gusennan** [data-8/zero-to-data-8#34]
Thank you for all the great materials you've been providing, both documentation and software. I came here from [the website's FAQ](https://berkeleydsep.gitbook.io/zero-to-data-8/content/misc/faq). If I should be asking this question somewhere else, please let me know.

We're using the edX versions of the data-8 lectures for a course we're teaching in this fall.  We've taught the course in the past and thus already have an instance of Jupyterhub running. While watching the edX lectures, I noticed that Berkeley's Jupyterhub had a `submit` button available for students to submit their assignments, while ours didn't.  My guess is that this is due to a version difference between the two Jupyterhub instances, or some custom plugin Berkeley developed.  We're running notebook server 5.6.0, whereas https://hub.data8x.berkeley.edu is running 5.7.3.  

How does one go about upgrading Jupyterhub to the later versions?  Do you have any insight into whether or not a later version contains this `submit` button that I refer to?

Thank you so much for any insight you may be able to provide.

**Comment by choldgraf** [comment]
hey there - thanks for reaching out!

I think that for general upgrading questions, your best bet is the Zero to JupyterHub guide: https://zero-to-jupyterhub.readthedocs.io/en/latest/upgrading.html

In this particular case, my intuition is that the "submit" button is more of a custom extension rather than a general JupyterHub feature. I don't believe that the ability to submit something is built into JupyterHub itself :-/ 

Maybe @ryanlovett or @yuvipanda would know more about the current configuration that results in the submit button?

**Comment by ryanlovett** [comment]
Hi @gusennan , do you have a link to the (video/screencast?) lecture that shows the submit button?

Based on your description I'd agree with @choldgraf that it is a feature of a notebook extension.

Edit: maybe [gofer-submit](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data8x/image/requirements.txt#L9)?

**Comment by gusennan** [comment]
Hi, and thanks for the responses! 

Sure, here's a [link to the first lab](https://hub.data8x.berkeley.edu/hub/user/2ea4d99efba7f4818d330ee52736ccfd/notebooks/materials-x19/materials/x19/lab/1/lab00/lab00.ipynb) in the "Foundations of Data Science: Computational Thinking with Python" course on edX.  I'm not sure if that link will work for you though, just because it looks like my user ID is embedded in the URL, but the python notebook making reference to the submit button is here:

https://github.com/data-8/materials-x19/blob/master/materials/x19/lab/1/lab00/lab00.ipynb

I've attached an image of the submit button as well.  Please let me know if I can provide any further information that would help, and thanks again!

![hub data8x berkeley edu-header](https://user-images.githubusercontent.com/624632/63399007-3223ce80-c39d-11e9-85db-272b3960e088.PNG)

**Comment by ryanlovett** [comment]
Yeah, that looks like [gofer-submit](https://github.com/data-8/gofer_submit).

Some other gofer-related projects: https://github.com/data-8?q=gofer

**Comment by gusennan** [comment]
Thanks so much for that information!
