### ISSUE TITLE
DSEP-Proposed Changes

### ISSUE THREAD

**Issue by alexnakagawa** [data-8/zero-to-data-8#38]
Hi @choldgraf !

This is Alex again from DSEP. We've outlined a document of some proposed changes that we're proposing to the textbook [here](https://docs.google.com/document/d/12c8FdfnlXY24zbdPrLFzaIoOxliOG3DyrrKKfkCWroY/edit?usp=sharing). 

The biggest change we're proposing here is to break the guide into two distinct guides: one focusing on technical infrastructure, and the second focusing solely on pedagogical considerations.

Let me know if you are ok with us submitting lots of PRs in the coming two weeks, or if you'd like to meet with us before we do so.

Cheers,
Alex

**Comment by choldgraf** [comment]
I think it's a great idea. Might I also suggest something else, which is to give a shot (either before or after updating the content) at building the book with the upcoming beta version of Jupyter Book:

https://beta.jupyterbook.org/

After the conversion it should be easier to get the toolchain up-and-running etc...

**Comment by alexnakagawa** [comment]
Since we're making large organizational changes, I'm proposing this workflow:

1. We submit PRs to a new branch called `dsep-changes` on this repository with all of the new `.md` files we are creating in a folder called `v2`
2. Once all the content is merged in, we reorganize the `_data/toc.yml` to point to the new content in `content/v2`, and move all of the old chapters into `content/v1`. Submit PR for organizational changes
3. Build using beta version and debug as necessary. PR for beta version changes
4. Merge to `master`, cross fingers!

Let me know if this makes sense or there's a better way to go about it.

**Comment by choldgraf** [comment]
go for it 👍

**Comment by alexnakagawa** [comment]
Thanks so much, would you be able to create the new branch titled `dsep-changes`? I tried to PR but this repo doesn't have a `dsep-changes` branch yet. Thanks in advance.

**Comment by choldgraf** [comment]
@alexnakagawa see my comment elsewhere about adding you as a maintainer. That should be enough to give you the freedom to make modifications as you see necessary. Does that work?

**Comment by alexnakagawa** [comment]
Many thanks (: will take good care in making sure things don't break.

**Comment by alexnakagawa** [comment]
Quick Update: moved all tech-related changes to a new book hosted on @ucbds-infra 
https://ucbds-infra.github.io/ds-course-infra-guide/intro.html now getting to work to making this guide more pedagogically focused!

**Comment by choldgraf** [comment]
cc @ryanlovett to make sure he's up-to-date on this progress, thanks for all this work @alexnakagawa

**Comment by alexnakagawa** [comment]
Thanks (: Hi, @ryanlovett would love your feedback on the newly launched DS Course Infra Guide: https://ucbds-infra.github.io/ds-course-infra-guide/intro.html. We're still working on removing data8-specific language inside of it so that it's generalizable to all types of courses.

**Comment by ryanlovett** [comment]
Thanks @choldgraf and hi @alexnakagawa ! I'm really glad this is being worked on.

Regarding the tech infrastructure bits, the part I most often point people at is what is currently in https://ucbds-infra.github.io/ds-course-infra-guide/jupyterhub/jupyterhub_devops.html#modifying-the-datahub. But I always have to tell people to ignore the data8-specific URLs. It will be very useful if the course-specific bits could be abstracted away so that we could point any of our course staff at it without having to qualify the content.

The whole doc is very Berkeley-specific, while the new title indicates that the material is more generally targeted at a Data Science educator. Is the goal to be institution agnostic? My hope is that the Zero-to-Data-8 book can become a Zero-to-{{ DSEP Course }} book and that if it were more generalized, it might have to dispense with some critical Berkeley-specific things.

**Comment by choldgraf** [comment]
Hey all, what is the status on these updates? I think as classes start to ramp up for fall, this could be a useful resource for other institutions

**Comment by alexnakagawa** [comment]
Thank you, @ryanlovett ! I’ve removed as many instances of a mention of data 8 as I could find in the tech guide (: there is one chapter focused soul on data 8 “as an example”, similar to the language Chris has on the previous guide.

@choldgraf , we’ve started to implement lots of the new chapters in #48 and #49 . They’ve gone through several edits by me so waiting for the team members to complete them.

Once those are in, I’d say we’re about 50% of the way through a completed pedagogy guide! Let me know if you’d like more information on what we’re doing as well. I can refer you to the doc that I attached to the first comment of this issue ^ but also am happy to explain it further as well.

**Comment by choldgraf** [comment]
Is the plan to complete the guide to 100% and then switch over the documentation? If so, could I suggest we instead start updating the master branch instead once we have a minimum-viable product, and then iteratively improving it over time? That way the content can be available for others to see even though it may still be evolving.

**Comment by alexnakagawa** [comment]
We can make the switch directly! I’ll take the afternoon to do that, just wanted to make sure I didn’t do something wrong to the chapters you wrote.

Alex Nakagawa

**Comment by choldgraf** [comment]
sounds good - is the same content there? Or has some stuff been removed?

How about we merge that pedagogy guide PR, and then make a switch. Then your team can work off of master and see the changes updated in real-time. I can also make a quick PR to get these docs working with the new jupyter book so there will be less complexity in the repository files

**Comment by choldgraf** [comment]
one other note - if it is helpful, I can spend some cycles merging, reviewing, etc PRs. Let me know if that would be welcome - I don't want to step on your toes though!

**Comment by alexnakagawa** [comment]
Thank you!! I've merged what we have so far. Luckily, we haven't been running the scripts to build the public files yet, so it was an easy merge.

A PR to get the new jupyter book library working with the current version of master would be really helpful.

**Comment by choldgraf** [comment]
awesome - OK I will put that together once https://github.com/data-8/zero-to-data-8/pull/49is merged in

**Comment by alexnakagawa** [comment]
Ok, everything should be working now! I thought I fixed everything, but realized that `content/` was still part of the path so I removed it today.

The repo itself looks a little disorganized, but it was necessary to follow the paths that looks best. Let me know if I should change anything!

**Comment by alexnakagawa** [comment]
Actually, something I'm noticing is that `runtime.txt` has 3.7, but the Github Actions script uses 3.8? Seems to have run fine, but just wanted to point that out in case something needs to be changed.

**Comment by alexnakagawa** [comment]
(Sorry for spamming) one more thing: I saw there's a new distribution of jupyter book, should i switch the `requirements.txt` to 0.7.0? https://github.com/executablebooks/jupyter-book/releases/tag/v0.7.0

EDIT: Made #58 to make the switch, let me know if this works!

**Comment by choldgraf** [comment]
no worries on the 3.7 vs 3.8 thing - we may wanna standardize it in the future but it's not a biggie...and thanks for the PR on the version. Shall we close this?

**Comment by alexnakagawa** [comment]
Sounds good! (: we made it to the end
