### ISSUE TITLE
Distinction between syllabus and textbook

### ISSUE THREAD

**Issue by ryanlovett** [data-8/zero-to-data-8#6]
Re: syllabus.md, I tend to think of inferentialthinking.com as the textbook and data8.org/<semester> as the syllabus. The latter links to the textbook, assignments, and all other course info. Should data8.org be mentioned here?

**Comment by choldgraf** [comment]
Good point - I'll take a pass through and see how I can clean that up, will ping here when it's done!

**Comment by choldgraf** [comment]
latest version more explicitly separates these two, so I think I'll close this, but reopen if you have other ideas!
