### ISSUE TITLE
Trouble Building -- problem with _toc.yml

### ISSUE THREAD

**Issue by sean-morris** [data-8/zero-to-data-8#61]
This looks like the toc needs to be migrated to a newer format. I updated the ["Create Data 8 Assignments"](https://github.com/data-8/zero-to-data-8/pull/60) page to reflect the current use of Otter-Grader in Data-8.

I am not sure if these are worth updating.

I tried to run the migrate command to no avail.

I guess two questions:
- Is there a quick way to get the toc formatted correctly?
- Is this worth pursuing?

I am seeing your name in the commit history Chris!
@choldgraf

**Comment by choldgraf** [comment]
Can you try these instructions to see if it works? It shouldn't be a ton of work, just renaming keys and some rearranging

https://github.com/executablebooks/jupyter-book/wiki/The-Jupyter-Book-Wiki#table-of-contents-structure

**Comment by sean-morris** [comment]
@choldgraf Got it. thanks for the pointer. All good.
