### ISSUE TITLE
introduce config.yaml

### ISSUE THREAD

**Issue by henchc** [data-8/zero-to-data-8#9]
I assume you were going to flesh it out, but the explanation of the [config](https://choldgraf.gitbooks.io/the-dsep-data-8-stack/content/z2d8/setup_k8s.html) file at the beginning is important. make sure to say that the config.yaml is a file on your local cloud shell and is used by helm to configure your hub. i think you can copy z2jh here.

**Comment by choldgraf** [comment]
Yeah I'm still not sure exactly how much to include in this guide, vs. when to link out to Z2JH - we're going to end up duplicating a lot of content if we write it all out in Z2D8, but perhaps we want to do this to keep it streamlined. What do you think?

**Comment by henchc** [comment]
unfortunately i think linking out too much would be confusing. i think the middle ground would be *very* short only-what-you-need-to-know synthesis from z2jh. If it's short enough, it wouldn't need to be updated much because it's big picture.

**Comment by choldgraf** [comment]
yeah fair point - the way we do this with BinderHub is to use an `.. include::` directive in the rST, but I don't know if this is compatible with gitbook. Else we can just copy/paste the minimum steps needed as you suggest.

**Comment by henchc** [comment]
ah, didn't know that was possible, if so, that sounds like a good solution, but parts might be a bit too much

**Comment by choldgraf** [comment]
Actually it's pretty neat, you can include only subsets of other pages if
you want, e.g. see this page and search for `.. include::`

https://raw.githubusercontent.com/jupyterhub/binderhub/master/doc/create-cloud-resources.rst
--

**Comment by choldgraf** [comment]
@henchc right now I'm trying to just solve this with linking out, here's the page:

https://choldgraf.gitbooks.io/the-dsep-data-8-stack/content/z2d8/setup_k8s.html

I started writing jhub setup instructions, then realized that this was gonna get complicated quickly as soon as people wanted to deploy on something other than google cloud etc. What do you think about the current solution (linking to each section of Z2JH specifically)?
